### ISSUE TITLE
[feature request] add  support for packing rocks in multiple dirs

### ISSUE THREAD

**Issue by DnPlas** [canonical/craft-actions#8]
At the moment, the action automatically packs rocks in the root of the repository where the action is called or from `path`, assuming the Rockcraft project is there, but there are repositories, for instance [pipelines-rocks](https://github.com/canonical/pipelines-rocks), where the root of the repository does not contain a Rockcraft project, and there are instead, multiple of them inside different directories.

**Comment by cjdcordeiro** [comment]
hi @DnPlas ! That sounds like a valid use case. I wonder however if it wouldn't be better to use a `matrix` in the GH workflow? You can have the different folders be inputs to the matrix. That would be much more efficient as all builds would happen in parallel (which would be much harder to do while guaranteeing performance, if we do it from within this action)

**Comment by DnPlas** [comment]
Yeah, that's fair and works.
